apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-course
  labels:
    app: dotnet-course
    kubernetes.azure.com/generator: devhub
  namespace: demo-ask-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-course
  template:
    metadata:
      labels:
        app: dotnet-course
    spec:
      containers:
        - name: dotnet-course
          image: sudhinazurecicd.azurecr.io/demo-dotnet-1728966115866:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
