apiVersion: v1
kind: Service
metadata:
  name: dotnet-course
  namespace: demo-ask-course
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: dotnet-course
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000